version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Check Node.js version
          command: node -v
      - run:
          name: Update npm to latest version
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          name: Restore dependencies from cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies if needed
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          name: Cache dependencies
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint with ESLint
          command: npx eslint . --ext=".js,.ts" --quiet
      - run:
          name: Typecheck with TSC
          command: npx tsc --noEmit
      - run:
          name: Test
          command: npx jest --ci --maxWorkers=2 --reporters="default" --reporters="jest-junit"
          environment:
            NODE_ENV: test
            JEST_JUNIT_OUTPUT_NAME: "reports/jest/result.xml"
      - store_test_results:
          path: reports
      - run:
          name: Build
          command: npm run build
